### ISSUE TITLE
go-to definitions replace current buffer

### ISSUE THREAD

**Issue by bcardarella** [emberwatch/vscode-ember#3]
When using a go-to definition the current buffer in active tab is replaced and there doesn't appear to be any way to get back to the original buffer. It would be better if a new tab was opened.

**Comment by t-sauer** [comment]
I think this is VSCode behaviour and (to my knowledge) there is nothing we can do.  
What I observed: Using go-to definition after I edited a file opens the definition in a new tab, while an unedited file gets replaced. So it is kinda like when you are clicking through the file explorer where VSCode always replaces unedited tabs.

It might be worth opening an issue in the VSCode repo.

**Comment by bcardarella** [comment]
Ah ok, I'm new to vscode. I don't mind the new buffer opening in the same tab but only if I can get back to the previous buffer. I haven't been able to find a way to do this.

I'll open an issue in vscode

**Comment by bcardarella** [comment]
For those looking: https://github.com/Microsoft/vscode/issues/29646#event-1141677567
