### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by kaermorchen** [emberwatch/vscode-ember#34]
Hi!

First of all, thanks to the team and Ember's community for a cool VSCode package.

What is the current status of this package and the original [ELS](https://github.com/ember-tooling/ember-language-server)? It looks like they are not supported.

![Screenshot 2023-05-31 at 11-07-22 Search results for ember Visual Studio Code on Visual Studio Marketplace](https://github.com/ember-tooling/vscode-ember/assets/11972062/67b86077-d745-4bde-a8a1-70f1ae202231)

A lot of people use them but don't know about [sESL](https://github.com/lifeart/vscode-ember) (second in the picture). Which is maintained and has a lot of more awesome features.

Maybe we should [deprecate](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#deprecating-extensions) this package in favor of sESL?

**Comment by evoactivity** [comment]
Hi @kaermorchen 

Work is happening now to consolodate the different extensions :)
