### ISSUE TITLE
Constant high CPU usage

### ISSUE THREAD

**Issue by muxcmux** [emberwatch/vscode-ember#4]
Hello, love the extension, but I have noticed that it would constantly hold my CPU at ~ 50%-60%, regardless of editor activity. `ps aux | grep [pid]` shows this:
```
muxcmux           9966  45.6  0.6  3287532 100736   ??  R    10:27am   0:19.76 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/muxcmux/.vscode/extensions/emberjs.vscode-ember-0.1.0/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/muxcmux/.vscode/extensions/emberjs.vscode-ember-0.1.0/node_modules/@emberwatch/ember-language-server/lib/start-server.js --node-ipc
```
Please let me know what sort of further info you need to help you debug this.
Thanks!

**Comment by sduquej** [comment]
Running into a similar problem. CPU consistently over 90%
![image](https://user-images.githubusercontent.com/1145726/31770678-ed24c492-b4d0-11e7-831d-db29e5a98588.png)

```
> ps aux | grep 2631
sebastianduque    2631 116.1  0.4  3265548  74044   ??  S    12:35pm  42:48.92 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/sebastianduque/.vscode/extensions/emberjs.vscode-ember-0.1.0/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/sebastianduque/.vscode/extensions/emberjs.vscode-ember-0.1.0/node_modules/@emberwatch/ember-language-server/lib/start-server.js --node-ipc
```

Quickly happens again after restarting VSCode

**Comment by nmccready** [comment]
Any updates, this is a serious problem.

**Comment by t-sauer** [comment]
I did some digging around a couple of weeks ago and found out, that just using chokidar will result in the high CPU usage (the more files exist in a project, the higher the cpu usage gets). We limit the watched files to a minimum so that's not something we could optimise.
The good thing I found out was, that with Node 8 the CPU usage of chokidar is way lower (went down from 40% to something below 2% on my machine in certain projects). Right now we use the Node version that is bundles with VSCode (which basically uses the version that comes with Electron.js which is 7.9 right now). We could either provide a way to use a custom node installation (so users could use their own node 8.x installations) or we just wait until Electron is upgrading to 8.x.

**Comment by nmccready** [comment]
Thanks for the reply. Is there any options for the ember watcher to disable watching certain directories? Does it already piggy back off the file and search settings in vscode preferences?

**Comment by nmccready** [comment]
Other thoughts; is it possible to use [watchman](https://facebook.github.io/watchman/)? Those settings are already available for ember apps.

**Comment by t-sauer** [comment]
There is no way to configure it right now. You can see what's currently ignored in the Language Server itself: https://github.com/emberwatch/ember-language-server/blob/master/src/server.ts#L80

About watchman: maybe that would help, but I think integrating watchman (plus a fallback for non-watchman users) is a pretty time consuming task and with the upcoming performance gain from node 8 I am not sure if it's worth it.

**Comment by nmccready** [comment]
I can confirm this workaround:

- Get [vscode insiders](https://code.visualstudio.com/insiders/) (beta/alpha).

- Use [syncing](https://marketplace.visualstudio.com/items?itemName=nonoroazoro.syncing) to save off your old vscode settings.

- Install syncing in vscode insiders and pull down new settings.

FIN

**Comment by nmccready** [comment]
So this is has gotten worse in insiders. Is there any progress on the way?

**Comment by t-sauer** [comment]
This should be fixed in the latest version.
