### ISSUE TITLE
`package.json` changes

### ISSUE THREAD

**Issue by evoactivity** [emberwatch/vscode-ember#43]
- [x] Will need name updating to `vscode-ember`
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L2

- [x] Description should be updated so it doesn't reference unstable
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L4

- [x] Publisher should be updated to `EmberTooling`
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L8
We control both namespaces on VSCode marketplace and OpenVSX
https://marketplace.visualstudio.com/publishers/EmberTooling
https://open-vsx.org/namespace/embertooling

- [x] Repo url needs updating
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L26
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L29

- [x] Update keywords to just `Language Server`
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L15

- [x] Configuration title should be updated to `Ember Language Server`
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L57

- [x] Resolutions need updating
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L140-L145

- [x] ember-language-server dependency needs updating
https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/package.json#L185

**Comment by lifeart** [comment]
@evoactivity do we planning to publish `ls` under `@ember-tooling/` or `@ember/` prefix? Or bare `ember-language-server`?

**Comment by evoactivity** [comment]
LS will be under `@ember-tooling/`
