### ISSUE TITLE
What's dotnet used for?

### ISSUE THREAD

**Issue by evoactivity** [emberwatch/vscode-ember#45]
@lifeart reviewing the workflow and I'm not sure what steps require dotnet?

https://github.com/ember-tooling/vscode-ember/blob/0dffe17457ecf2c00c55dfcd5cb60cd8e836cbf7/.github/workflows/workflow.yaml#L21

**Comment by lifeart** [comment]
@evoactivity it's used for next step (`gitversion`), it's works on `.net`

**Comment by evoactivity** [comment]
Hmm. vsc-ember-syntax uses gitversion without needing a step for installing dotnet?
https://github.com/lifeart/vsc-ember-syntax/blob/master/.github/workflows/workflow.yaml

**Comment by lifeart** [comment]
@evoactivity yep, both flows landed in same time, and can't say one better than another, likely we need to explore plate for up-to date options (may be from different frameworks of JS ecosystem)

**Comment by evoactivity** [comment]
Yep, that is being discussed here https://github.com/orgs/ember-tooling/discussions/1
I think changesets is probably the way to go, unless something lands in `release-plan` to use a custom publish step.
